---
# tasks file for ansible-manage-lvm
- include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- include_tasks: centos.yml
  when: ansible_os_family == "RedHat"

- include_tasks: manage_lvm.yml
  when: >
        manage_lvm and
        lvm_groups is defined
